name: Build
on:
  push:
    branches:
    - main
    - dev/*
    - feature/*
    - fix/*
    tags:
    - 'endpoint/v[0-9]+.[0-9]+.[0-9]+'
    paths:
    - 'endpoint/**'
    - '!endpoint/**.md'
    - '!endpoint/scripts/**'
  pull_request:
    branches:
    - main
    paths:
    - 'endpoint/**'
    - '!endpoint/**.md'
    - '!endpoint/scripts/**'
  workflow_dispatch:

jobs:
  test:
    uses: ./.github/workflows/test.yaml
    with:
      working-directory: endpoint
